# Generated by Django 4.2.1 on 2023-05-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('amminity', models.CharField(choices=[('', 'Chooce Amminities'), ('Swimming', 'swimming'), ('wifi', 'wifi'), ('free Lunch', 'free Lunch'), ('parking space', 'parking space'), ('event space', 'event space')], max_length=100, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.location')),
            ],
        ),
    ]
