# Generated by Django 4.2.1 on 2023-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_menu_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='hotel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
