# Generated by Django 4.2.1 on 2023-05-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_menu_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='hotel',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='pic',
        ),
    ]
