# Generated by Django 4.2.1 on 2023-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hotel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='checkIn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='checkOut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='guest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
