# Generated by Django 4.2.1 on 2023-05-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hotel_checkin_hotel_checkout_hotel_guest_hotel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='checkIn',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkOut',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
    ]
