# Generated by Django 4.2.1 on 2023-05-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_hotel_checkin_remove_hotel_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='book',
        ),
    ]
