# Generated by Django 4.2.1 on 2023-05-09 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_amminities_remove_hotel_amminity_hotel_amminity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bio',
            field=models.TextField(default=datetime.datetime(2023, 5, 9, 6, 22, 17, 334668, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
