# Generated by Django 4.2.1 on 2023-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_location_bio_location_pic_alter_hotel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
