# Generated by Django 4.2.1 on 2023-05-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_location_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='menu',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='home.hotel'),
        ),
    ]
