# Generated by Django 4.2.1 on 2023-05-07 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('guest', models.CharField(max_length=100, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.hotel')),
            ],
        ),
    ]
