# Generated by Django 4.2.1 on 2023-05-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_hotel_menu_hotel_name_rename_image_menu_pic'),
        ('booking', '0003_alter_booking_booker'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.hotel'),
        ),
    ]
