# Generated by Django 4.2.1 on 2023-05-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='place',
            new_name='hotel',
        ),
    ]
