# Generated by Django 4.2.1 on 2023-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('desc', models.TextField(null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('author_bio', models.TextField(null=True)),
                ('author_pic', models.ImageField(null=True, upload_to='media')),
                ('publish_date', models.DateField(null=True)),
                ('approved', models.BooleanField()),
                ('tag', models.ManyToManyField(to='blog.tag')),
            ],
        ),
    ]
