# Generated by Django 4.2.1 on 2023-05-09 14:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'select tag'), ('Mountain', 'Mountain'), ('solo trip', 'solo trip'), ('family trip', 'family trip'), ('Get-Together', 'Get-Together'), ('others', 'others')], max_length=100, null=True),
        ),
    ]
